- hosts: remote
  gather_facts: no
  remote_user: root

  vars_prompt:
    - name: packages
      prompt: Quels packages voulez vous installer ?
      private: no
  
  tasks:
    - set_fact:
       packages_list: "{{ packages.split(',') }}"
    
    - name: install packages 
      package: 
        name: "{{ packages_list }}" 
        state: present
      become: true
      ansible_become_password:     

