- hosts: remote
  gather_facts: no

  vars_prompt:
    - name: packages
      prompt: Quels packages voulez vous installer ?
      private: no
  
  tasks:
    - set_fact:
       packages_list: "{{ packages.split(',') }}"
    
    - name: install packages 
      package: 
        name: "{{ packages_list }}" 
        state: present
      become: true
<<<<<<< HEAD:playbook.td.yml
      ansible_become_password:     
=======

          
>>>>>>> e11e7c6b6cf8f64c5664a649a5588f38040fb69e:exos/playbook.td.yml

