- hosts: remote
  gather_facts: false 
  vars:
    fichier: test.txt
    destination: /home/ansible_user/test5.txt
  tasks:
    - name: test ping
      ping:

    - name: copy file to remote server
      copy:
        src: "{{ fichier }}"
        dest: "{{ destination }}"

#ajout d'un commentaire




