---
# tasks file for subnet
- name: Create a subnet
  azure_rm_subnet:
    resource_group: "{{ myResourceGroup }}"
    virtual_network_name: "{{ myVirtualNetwork }}"
    name: "{{ mySubnet }}"
    address_prefix_cidr: "{{ ipCidrSubnet }}"